services:
  node1:
    build: .
    container_name: raft_node1
    command: ["./app/nodeApp", "1", "/node/config.json"]
    ports:
      - "50001:50001"
    volumes:
      - "./data/node1:/data"

  node2:
    build: .
    container_name: raft_node2
    command: ["./app/nodeApp", "2", "/node/config.json"]
    ports:
      - "50002:50002"
    volumes:
      - "./data/node2:/data"

  node3:
    build: .
    container_name: raft_node3
    command: ["./app/nodeApp", "3", "/node/config.json"]
    ports:
      - "50003:50003"
    volumes:
      - "./data/node3:/data"