services:
  node1:
    build: .
    container_name: raft_node1
    command: ["./app/nodeApp", "1", "/node/config.json"]
    ports:
      - "50001:50001"
      - "8081:8080"
    volumes:
      - "./data/node1:/data"

  node2:
    build: .
    container_name: raft_node2
    command: ["./app/nodeApp", "2", "/node/config.json"]
    ports:
      - "50002:50002"
      - "8082:8080"
    volumes:
      - "./data/node2:/data"

  node3:
    build: .
    container_name: raft_node3
    command: ["./app/nodeApp", "3", "/node/config.json"]
    ports:
      - "50003:50003"
      - "8083:8080"
    volumes:
      - "./data/node3:/data"

  node4:
    build: .
    container_name: raft_node4
    command: [ "./app/nodeApp", "4", "/node/config.json" ]
    ports:
      - "50004:50004"
      - "8084:8080"
    volumes:
      - "./data/node4:/data"

  node5:
    build: .
    container_name: raft_node5
    command: [ "./app/nodeApp", "5", "/node/config.json" ]
    ports:
      - "50005:50005"
      - "8085:8080"
    volumes:
      - "./data/node5:/data"